services:
  postgres:
    image: postgres:16
    container_name: postgres_16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network
    command: >
      postgres
      -c listen_addresses='*'
      -c shared_preload_libraries=pg_stat_statements
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
  adminer:
    image: adminer:latest
    container_name: adminer-latest
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-5433}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_DB: ${DB_NAME:-postgres}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-network

volumes:
  postgres_data:
    name: postgres_data

networks:
  postgres-network:
    name: postgres_network
    driver: bridge